### ISSUE TITLE
Flasher SD Card download does not see data partition of SD Card

### ISSUE THREAD

**Issue by phileville** [EdgeTX/flasher#12] opened 2021-06-26 20:09 UTC
I tried the SD Card downloader in the latest flasher - it does not detect the SD card data partition, just the Firmware partition, even though in windows explorer I can see both.  If I put a SD card in my laptops built in card reader, it will see it, but not when it is in the radio and connected via USB.

**Comment by pfeerick** [comment] 2021-06-27 02:37
I think this is duplicate of #10

**Comment by CoderElectronics** [comment] 2021-07-01 02:59
Ok this should be all fixed, i removed the drive label filter, it should be working now. Please re-open if it doesn't see it

**Closed** 2021-07-01 02:59 UTC
